"""Initial operation workflow audit and emoji schema"""

from alembic import op
import sqlalchemy as sa

revision = "2190ad7fc7bb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("mime", sa.String(length=120), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_sha256"), "assets", ["sha256"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=True),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_at"), "audit_events", ["at"], unique=False)
    op.create_index(op.f("ix_audit_events_resource_id"), "audit_events", ["resource_id"], unique=False)
    op.create_table(
        "emoji_roles",
        sa.Column("role", sa.String(length=80), nullable=False),
        sa.Column("emoji_id", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("role"),
    )
    op.create_table(
        "emojis",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("pack", sa.String(length=150), nullable=True),
        sa.Column("alt", sa.String(length=100), nullable=True),
        sa.Column("file_id", sa.Text(), nullable=True),
        sa.Column("format", sa.String(length=10), nullable=True),
        sa.Column("asset_id", sa.String(length=32), nullable=True),
        sa.Column("preview_id", sa.String(length=32), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=True),
        sa.Column("reviewed", sa.Boolean(), nullable=True),
        sa.Column("error", sa.String(length=250), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_emojis_pack"), "emojis", ["pack"], unique=False)
    op.create_table(
        "operations",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("method", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column("approved_by", sa.String(length=80), nullable=True),
        sa.Column("approved_digest", sa.String(length=64), nullable=True),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("workflow_run_id", sa.String(length=32), nullable=True),
        sa.Column("step_index", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index(op.f("ix_operations_created_at"), "operations", ["created_at"], unique=False)
    op.create_index(op.f("ix_operations_run_at"), "operations", ["run_at"], unique=False)
    op.create_index(op.f("ix_operations_status"), "operations", ["status"], unique=False)
    op.create_index(op.f("ix_operations_workflow_run_id"), "operations", ["workflow_run_id"], unique=False)
    op.create_table(
        "runtime_state",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "telegram_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.JSON(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workflow_id", sa.String(length=32), nullable=True),
        sa.Column("occurrence_key", sa.String(length=100), nullable=True),
        sa.Column("steps", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("cursor", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "occurrence_key"),
    )
    op.create_index(op.f("ix_workflow_runs_workflow_id"), "workflow_runs", ["workflow_id"], unique=False)
    op.create_table(
        "workflows",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("trigger", sa.JSON(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=True),
        sa.Column("approved_digest", sa.String(length=64), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("next_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=True),
        sa.Column("max_runs", sa.Integer(), nullable=True),
        sa.Column("runs_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflows_next_run"), "workflows", ["next_run"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflows_next_run"), table_name="workflows")
    op.drop_table("workflows")
    op.drop_index(op.f("ix_workflow_runs_workflow_id"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_table("telegram_updates")
    op.drop_table("runtime_state")
    op.drop_index(op.f("ix_operations_workflow_run_id"), table_name="operations")
    op.drop_index(op.f("ix_operations_status"), table_name="operations")
    op.drop_index(op.f("ix_operations_run_at"), table_name="operations")
    op.drop_index(op.f("ix_operations_created_at"), table_name="operations")
    op.drop_table("operations")
    op.drop_index(op.f("ix_emojis_pack"), table_name="emojis")
    op.drop_table("emojis")
    op.drop_table("emoji_roles")
    op.drop_index(op.f("ix_audit_events_resource_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_assets_sha256"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
