"""scoped agent grants expiring approval ownership and audit correlation"""
from alembic import op
import sqlalchemy as sa
revision = '3ad7b764f596'
down_revision = '54904c330b77'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=80), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_grants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('preset', sa.String(length=16), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('chats', sa.JSON(), nullable=False),
    sa.Column('methods', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=False),
    sa.Column('daily_operations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_subject'),
    sa.UniqueConstraint('secret_hash')
    )
    op.create_table('rate_buckets',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_rate_buckets_expires_at'), 'rate_buckets', ['expires_at'], unique=False)
    op.add_column('assets', sa.Column('actor', sa.String(length=80), server_default='owner', nullable=False))
    op.add_column('audit_events', sa.Column('request_id', sa.String(length=32), nullable=True))
    op.add_column('audit_events', sa.Column('trace_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_trace_id'), 'audit_events', ['trace_id'], unique=False)
    op.add_column('operations', sa.Column('approved_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_runs', sa.Column('actor', sa.String(length=80), server_default='owner', nullable=False))
    op.add_column('workflows', sa.Column('actor', sa.String(length=80), server_default='owner', nullable=False))
    op.add_column('workflows', sa.Column('approved_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'approved_until')
    op.drop_column('workflows', 'actor')
    op.drop_column('workflow_runs', 'actor')
    op.drop_column('operations', 'approved_until')
    op.drop_index(op.f('ix_audit_events_trace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_column('audit_events', 'trace_id')
    op.drop_column('audit_events', 'request_id')
    op.drop_column('assets', 'actor')
    op.drop_index(op.f('ix_rate_buckets_expires_at'), table_name='rate_buckets')
    op.drop_table('rate_buckets')
    op.drop_table('agent_grants')
    op.drop_table('admin_requests')
    # ### end Alembic commands ###
