"""Fence worker completions against stale leases"""
from alembic import op
import sqlalchemy as sa
revision = '54904c330b77'
down_revision = '2190ad7fc7bb'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('execution_token', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'execution_token')
    # ### end Alembic commands ###
