"""correlate operation execution traces"""
from alembic import op
import sqlalchemy as sa
revision = '9906fa12eb62'
down_revision = '3ad7b764f596'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('trace_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_operations_trace_id'), 'operations', ['trace_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_trace_id'), table_name='operations')
    op.drop_column('operations', 'trace_id')
    # ### end Alembic commands ###
